#!/usr/bin/python
# -*- coding: utf-8 -*-

MY_ROBOT_NAME="RobotReal"
PDU_BAGGAGE_CHANNEL_ID = 0
PDU_BUMPER_CHANNEL_ID = 1
PDU_MOTOR_CHANNEL_ID = 2

AVATAR_NAME = "RobotAvator"
PDU_POS_CHANNEL_ID = 0
PDU_BAGGAGE_CHANNEL_ID = 1
PDU_BUMPER_CHANNEL_ID = 2
